apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu request for container
      elasticsearch'
  creationTimestamp: 2019-01-03T09:11:10Z
  generateName: elasticsearch-
  labels:
    app: jaeger-elasticsearch
    controller-revision-hash: elasticsearch-8684f69799
    jaeger-infra: elasticsearch-replica
    statefulset.kubernetes.io/pod-name: elasticsearch-0
  name: elasticsearch-0
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: elasticsearch
    uid: 86578784-0f36-11e9-b8b1-42010aa60019
  resourceVersion: "2778"
  selfLink: /api/v1/namespaces/default/pods/elasticsearch-0
  uid: 82d3be2f-0f37-11e9-b8b1-42010aa60019
spec:
  containers:
  - args:
    - -Ehttp.host=0.0.0.0
    - -Etransport.host=127.0.0.1
    - -cpus
    - "2"
    command:
    - bin/elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
    imagePullPolicy: Always
    name: elasticsearch
    readinessProbe:
      exec:
        command:
        - curl
        - --fail
        - --silent
        - --output
        - /dev/null
        - --user
        - elastic:changeme
        - localhost:9200
      failureThreshold: 3
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 4
    resources:
      limits:
        cpu: "1"
      requests:
        cpu: "0.5"
        # container has a request of 0.5  CPU 
        #cpu: 100m
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /data
      name: data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-96vwj
      readOnly: true
  dnsPolicy: ClusterFirst
  hostname: elasticsearch-0
  nodeName: gke-jaeger-persistent-st-default-pool-81004235-h8xt
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  subdomain: elasticsearch
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: data
  - name: default-token-96vwj
    secret:
      defaultMode: 420
      secretName: default-token-96vwj
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2019-01-03T09:11:10Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2019-01-03T09:11:40Z
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2019-01-03T09:11:10Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://46eb2c664f947a2a0a35ac7799b04c77756aef0a9935855c2dadcf959bd27030
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.0
    imageID: docker-pullable://docker.elastic.co/elasticsearch/elasticsearch@sha256:f95e7d4256197a9bb866b166d9ad37963dc7c5764d6ae6400e551f4987a659d7
    lastState: {}
    name: elasticsearch
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: 2019-01-03T09:11:13Z
  hostIP: 10.166.0.2
  phase: Running
  podIP: 10.36.0.10
  qosClass: Burstable
  startTime: 2019-01-03T09:11:10Z