apiVersion: v1
kind: Pod
metadata:
  name: test-pd4
spec:
  containers:
  - image: k8s.gcr.io/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    # This GCE PD must already exist.
    gcePersistentDisk:
      pdName: gke-jaeger-persistent--pvc-6ecfa54c-09d2-11e9-bbfc-42010a9a00c0
      fsType: ext4