apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-configuration
  labels:
    app: jaeger
    jaeger-infra: configuration
data:
  #span-storage-type: cassandra
  span-storage-type: elasticsearch
  collector: |
    collector:
      # I am adding this
      # https://github.com/jaegertracing/jaeger-performance/blob/master/openshift/templates/configmap-elasticsearch.yml
      num-workers: ${COLLECTOR_NUM_WORKERS}
      queue-size: ${COLLECTOR_QUEUE_SIZE}
      # End 
      
      zipkin:
        http-port: 9411

    # I am adding this
    # https://github.com/jaegertracing/jaeger-kubernetes/blob/master/production-elasticsearch/configmap.yml
    es:
      server-urls: https://c385ec84452f4376aec843134faf49f2.europe-west1.gcp.cloud.es.io:9243/
      username: elastic 
      password: AicZt4YAxu2VcY1qssNhUgss
      # Encypt it may be ?
    # End 
    
    # I am commenting this
    # cassandra:
      # servers: cassandra
      # keyspace: jaeger_v1_dc1
    # End

  query: |
    # I am adding this
    query:
      static-files: ${QUERY_STATIC_FILES}
      port: 16686
    es:
      server-urls: https://c385ec84452f4376aec843134faf49f2.europe-west1.gcp.cloud.es.io:9243/
      bulk:
        size: ${ES_BULK_SIZE}
        workers: ${ES_BULK_WORKERS}
        flush-interval: ${ES_BULK_FLUSH_INTERVAL}
    # End

    # I am commenting this
    # cassandra:
      # servers: cassandra
      # keyspace: jaeger_v1_dc1
    # End
  agent: |
    collector:
      host-port: "jaeger-collector:14267"