kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: jaeger-data
provisioner: kubernetes.io/gce-pd

parameters:
  type: pd-ssd
  fsType: ext4
reclaimPolicy: Retain



# About of storage class
# https://kubernetes.io/docs/concepts/storage/storage-classes/

# View more storage class provisioner types
# https://kubernetes.io/docs/concepts/storage/storage-classes/#provisioner

# gce-pd provisioner
# https://kubernetes.io/docs/concepts/storage/storage-classes/#gce-pd

# Parameters
# https://kubernetes.io/docs/concepts/storage/storage-classes/#parameters
