apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jaeger-vol
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: jaeger-data

  # I can change the namespace and take in my mind the other jaeger components
  # which are in the default namespace